apiVersion: v1
kind: Service
metadata:
  name: product-inventory-api-service
spec:
  selector:
    app: product-inventory-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: product-inventory-api
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: NodePort
